[default]
# --- General Settings ---
border=no
autofit-larger=60%x60%
osd-scale=1.0
osd-font-size=30
osd-bar=no
keep-open=no
save-position-on-quit=yes
volume-max=150

# --- Default Subtitle Style ---
sub-font="Tahoma"
sub-font-size=26
sub-bold=no
sub-color="#FFFFFF"
sub-border-size=0.1
sub-border-color="#FF000000"
sub-shadow-color="#FF000000"
sub-shadow-offset=0
sub-blur=3
sub-margin-x=100
sub-margin-y=30

# --- Behaviour ---
sub-auto=fuzzy
sub-fix-timing=yes

# --- Screenshot Settings ---
screenshot-format=png
screenshot-template="~~/screenshots/%{filename/no-ext}-%{time-pos:hms}-%#00n"
screenshot-png-compression=2
screenshot-png-filter=5
screenshot-high-bit-depth=no

# Recommended quality profile
profile=high-quality

# --- Video Output Settings ---
vo=gpu-next
gpu-api=vulkan

# Hardware acceleration
hwdec=yes

# Audio settings
audio-exclusive=no
audio-channels=auto-safe

# --- Subtitle profiles ---
[anime]
sub-font="Candara"
sub-font-size=40
sub-bold=yes
sub-color="#FFFFFF"
sub-border-size=2.2
sub-border-color="#FF000000"
sub-shadow-color="#FF000000"
sub-shadow-offset=0
sub-blur=0.7
sub-margin-x=100
sub-margin-y=30

[film]
sub-font="Tahoma"
sub-font-size=26
sub-bold=no
sub-color="#FFFFFF"
sub-border-size=0.1
sub-border-color="#FF000000"
sub-shadow-color="#FF000000"
sub-shadow-offset=0
sub-blur=3
sub-margin-x=100
sub-margin-y=30